language: generic
  # sudo: required
  # dist: trusty
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    # - EMACS=emacs24
    - EMACS=emacs-snapshot

branches:
  # allow_failures:
  #   - env: EMACS=emacs-snapshot
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs-snapshot &&
      sudo apt-get -qq install emacs-snapshot-el;
    fi
  - $EMACS --version
  # requires
  # - $CURL (url) -o lib.el

script:
  - $EMACS --batch --eval '(progn (push "." load-path) (byte-compile-file "vagrant.el"))'
  # - $EMACS -batch -L . -l ert -l -test/tests.el -f  ert-run-tests-batch-and-exit
        
